# -*- coding: utf-8 -*-
"""Untitled87.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydbT1WlOVKT2vMgjoC3dhZ4FBDv0AQy8
"""

# ====================================================================

ENHANCED_INTUITIVE_PROMPT = """
You are a mathematical hardness analyst and expert resource predictor. Your role is to evaluate difficulty and predict the required token budget by performing a comprehensive, **meta-reasoning synthesis.**

[REFERENCE ANCHORS]
{examples}

Problem: {problem_text[:400]}...

Step 1: **Categorization and Structural Analysis**
**First, classify the problem (e.g., Algebra, Geometry, Combinatorics, Number Theory).** Next, identify the core principles. **Identify any recurring mathematical forms or subtle patterns that suggest either a short solution using identity/induction, or a long solution requiring deep recursive steps.**

Step 2: Break down the problem into its main components verbally.

Step 3: Rate each standard parameter on a 1-10 scale:
- Conceptual Depth: Prerequisite knowledge level
- Computational Effort: Calculation complexity
- Abstraction Level: Real-world detachment
- Heuristic Requirements: Creative strategies needed
- Constrainedness: Solution space narrowness

Step 4: **Complexity Assessment and Special Characteristics**
Identify any unique features that affect token usage but are not captured by standard parameters. **Critically assess the forward-looking complexity: Does the problem structure suggest a lengthy, iterative validation process (like many case analyses or recursive steps), which would significantly increase the final token count?**

Step 5: Compare your analysis to the Reference Anchors.
- Is this problem easier or harder than Example 1? By how much?
- Where does it fall relative to Example 2? **When comparing, focus on *why* a successful anchor required its cost (long setup, complex intermediate steps, detailed final proof) to inform your current prediction.**

Step 6: **Final Synthesis and Budget Output**
Based on this comprehensive analysis, including your parameter ratings, the problem category, the complexity assessment, and the anchor comparisons, output the final token budget.
(Use the examples as calibration points, not fixed rules)

Format your answer exactly as:
[CONCEPTUAL_DEPTH] X
[COMPUTATIONAL_EFFORT] X
[ABSTRACTION] X
[HEURISTIC] X
[CONSTRAINEDNESS] X
[TOKENS] X
"""